application: giolekva
version: 3caching
runtime: python
api_version: 1

default_expiration: "32d"

handlers:
- url: /static
  static_dir: static

- url: /demo
  static_dir: demo
  
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /favicon.ico
  static_files: static/favicon.png
  upload: static/favicon.png
  
- url: /import
  script: main.py
  login: admin
  
- url: /edit
  script: main.py
  login: admin
  
- url: /clear_datastore
  script: main.py
  login: admin
  
- url: /calculate_comments
  script: main.py
  login: admin

- url: /admin
  script: main.py
  login: admin

- url: /tags
  script: main.py
  login: admin

- url: /.*
  script: main.py
  