runtime: python27
api_version: 1
threadsafe: true

default_expiration: "32d"

handlers:
- url: /static
  static_dir: static

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /favicon.ico
  static_files: static/favicon.png
  upload: static/favicon.png

- url: /import_json
  script: main.app
  login: admin

- url: /import
  script: main.app
  login: admin

- url: /edit
  script: main.app
  login: admin

- url: /clear_datastore
  script: main.app
  login: admin

- url: /calculate_comments
  script: main.app
  login: admin

- url: /admin
  script: main.app
  login: admin

- url: /tags
  script: main.app
  login: admin

- url: /.*
  script: main.app
